version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: google.golang.org/protobuf
    versions:
    - 1.25.0
