language: go

go:
  - stable

install: true

script:
  - go test -v -cover -covermode=atomic -coverprofile=tests.out ./...

after_success:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=tests.out -service travis-ci -repotoken $COVERALLS_TOKEN
